version: '3.4'

services:
  companyandemployeedb:
    container_name: companyandemployeedb
    environment:
        SA_PASSWORD: "sabbir123"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
 
  footballteamsandplayersdb:
    container_name: footballteamsandplayersdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=29022004bd
      - POSTGRES_DB=Football
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  footballleagueandclubsdb:
    container_name: footballleagueandclubsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=29022004bd
      - POSTGRES_DB=FootballLeaguesAndClubs
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"


  companyandemployee.api:
    container_name: companyandemployee.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=sabbir123"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672" 
    depends_on:
      - companyandemployeedb
    ports:
      - "8000:80"

  footballteamsandplayers.api:
    container_name: footballteamsandplayers.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings: ConnectionString=Host=localhost;Port=5432;Database=Football;Username=postgres;Password=29022004bd;"
    depends_on:
      - footballteamsandplayersdb
    ports:
      - "8001:80"

  footballleagueandclubs.api:
    container_name: footballleagueandclubs.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings: ConnectionString=Host=localhost;Port=5432;Database=FootballLeaguesAndClubs;Username=postgres;Password=29022004bd;"
    depends_on:
      - footballleagueandclubsdb
    ports:
      - "8002:80"



  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
