version: '3.4'

services:

  companyandemployeedb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  footballteamsandplayersdb:
    image: postgres

  footballleagueandclubsdb:
    image: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce 

  companyandemployee.api:
    image: ${DOCKER_REGISTRY-}companyandemployeeapi
    build:
      context: .
      dockerfile: Services/Basket/WebApi/Dockerfile

  footballteamsandplayers.api:
    image: ${DOCKER_REGISTRY-}footballteamsandplayersapi
    build:
      context: .
      dockerfile: Services/Catalog/WebApi/Dockerfile

  footballleagueandclubs.api:
    image: ${DOCKER_REGISTRY-}footballleagueandclubsapi
    build:
      context: .
      dockerfile: Services/Ordering/UnitOfWorkDemo/Dockerfile

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:



